name: Stojan Dimitrovski
markdown: kramdown
highlighter: rouge

exclude:
  - assets/scss
  - graphics

assets:
  main:
    v: ?v1
  zepto:
    v: ?v1.1.3
  i:
    v: ?v2
  syntax:
    v: ?v1

encoding: utf-8

permalink: /i/:categories/:i_day/:i_month/:year/:title

author:
  twitter: stojaaan
  linkedin: stojan-dimitrovski-49530024
  github:  hf

url: http://stojan.me

kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
