name: Stojan Dimitrovski
markdown: redcarpet
pygments: true

exclude:
  - assets/scss
  - graphics

encoding: utf-8

permalink: /i/:categories/:i_day/:i_month/:year/:title

author:
  twitter: stndim
  gplus: https://plus.google.com/116831509108871035346

url: //hf.github.io
